# Dependencies
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate, jekyll-gist]

# Setup
title:            Ravi Yadav
description:      "The personal site of Ravi Yadav. Views expressed are my own. Use code at your own risk!"
url:              http://www.yravi.com

# author:
#   name:           'Ravi Yadav'
#   # url:            https://twitter.com/raavyadav

paginate:         5

# Custom vars
version:          2.0.0
