# Dependencies
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate, jekyll-gist]

# Setup
title:            Ravi Yadav
tagline:          'A Jekyll theme'
description:      ''
url:

author:
  name:           'Ravi Yadav'
  url:            https://twitter.com/raavyadav

paginate:         5

# Custom vars
version:          2.0.0
